### ISSUE TITLE
Feature: specify find command

### ISSUE THREAD

**Issue by TymekDev** [tpope/vim-eunuch#102]
Hi! I wonder if hard coded find command could be replaced with something like:
```vim
get(g:, 'eunuch_find_command', 'find')
```
to allow its parameterisation.

**Comment by tpope** [comment]
No, see #94.

**Comment by TymekDev** [comment]
Yep, I saw it. It didn't have the thumbs down on option proposal at the time though. #94 makes the selected command dependent on user's system environment, and is a potentially breaking change. I am suggesting making it configurable via a vim variable without meddling with current functionality.

**Comment by tpope** [comment]
A config option isn't utterly deranged like the original proposal, but it still has terrible vibes:

```vim
let g:eunuch_apples_command = 'oranges'
```

The correct solution is to allow the user to create arbitrary commands, which I will consider when I eventually retool to use jobs. In the meantime, it isn't _that_ much you need to copy and paste to do this yourself.
