### ISSUE TITLE
Why does Unlink Remove files?

### ISSUE THREAD

**Issue by anakimluke** [tpope/vim-eunuch#103]
Not an issue per se.  I'm just curious why you chose the work "unlink" to mean the same as to "remove". I accidentally removed a (version controlled) file because of it ;)

**Comment by tpope** [comment]
See `man 2 unlink`. This is the historical UNIX name for the operation. This name actually felt _less_ confusing to me when I came up with it, because while "delete" and "remove" could refer to many things, "unlink" could only refer to deleting a file in particular.
