### ISSUE TITLE
Add support for doas(1) in addition to sudo(1)

### ISSUE THREAD

**Issue by teoljungberg** [tpope/vim-eunuch#105]
On an OpenBSD system sudo(1) is not installed by default, but doas(1) is. Making `:SudoEdit` and `:*Write` not work out of the box.

Is adding support for doas in addition to sudo something we'd consider? If so, how would you suggest it be implemented?

**Comment by UrsaDK** [comment]
The same goes for Alpine Linux. It too uses `doas` instead of `sudo`.

**Comment by tpope** [comment]
My instinct is to say no. The existing `sudo` support turned out to way harder to iron out all the kinks than I expected. Doing that journey a second time, but this time with a tool I don't even use, doesn't seem like a good idea.
