### ISSUE TITLE
CR mapping doesn't handle `<expr>` neovim-lua-callback keybindings.

### ISSUE THREAD

**Issue by altermo** [tpope/vim-eunuch#108]
Neovim has the possibility of setting keymaps to a lua-functions. The problem arises when the keymap is an `<expr>` cause then vim-eunuch uses `maparg().rhs` which is not set for lua-callback keybindings, which causes `<CR>` not to work.
Example:
```lua
for name, url in pairs{
    'https://github.com/tpope/vim-eunuch'
} do
  local install_path = vim.fn.fnamemodify('nvim_issue/'..name, ':p')
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
  vim.opt.runtimepath:append(install_path)
end
vim.keymap.set('i','\r',function () return '\r' end,{expr=true})
```
This bug mainly affects autocompletion and auto-pairing plugins.

**Comment by tpope** [comment]
Okay.
