### ISSUE TITLE
Why does `:Wall a` call a system broadcast app?

### ISSUE THREAD

**Issue by idbrii** [tpope/vim-eunuch#111]
If you pass arguments to `:Wall`, it doesn't write files but instead calls the system's `wall` command which [messages all logged-in users](https://en.wikipedia.org/wiki/Wall_(Unix)).

https://github.com/tpope/vim-eunuch/blob/084946fb1c8103ae0cb7342e9be3a2c69374958c/plugin/eunuch.vim#L349-L354

I don't understand why you'd ever want to use a `system()` call with a write command. It doesn't look like calling `wall` is likely to succeed since it expects input on stdin.

**Comment by tpope** [comment]
As revealed by `git blame`, it's an [easter egg](https://github.com/tpope/vim-eunuch/commit/9f63df9fffaa10f9b8c2941c2b14ff0cff0c9fc6).

> It doesn't look like calling `wall` is likely to succeed since it expects input on stdin.

It's being given input on stdin.
