### ISSUE TITLE
Blocked <cr>

### ISSUE THREAD

**Issue by savchenko** [tpope/vim-eunuch#113]
Potentially related to https://github.com/tpope/vim-eunuch/issues/108

I have noticed that having both `eunuch` and https://github.com/windwp/nvim-autopairs enabled at the same time results in <cr> returning `nil` in the insert mode.

Disabling `eunuch` fixes it. Any clues?

**Comment by tpope** [comment]
Appears to be the same as https://github.com/windwp/nvim-autopairs/issues/430 and fixed by https://github.com/windwp/nvim-autopairs/commit/d4aef9dbfecefb76ff0a302100c2eae8f79d2144.
