### ISSUE TITLE
Eunuch-passive behaviour overrides delimitMate expand_cr

### ISSUE THREAD

**Issue by Alejandro-Roldan** [tpope/vim-eunuch#116]
as title says.
delimitMate when pressing <CR> inside delimiters and ```delimitmate_expand_cr = 1``` expands it from ```{|}``` to ```{\n\t|\n}```

Had a look at the code but i don't know enough vim scripting to figure a solution
Wanted to at least add a var that lets deactivate the passive behaviour but even that can't figure out. I was confused by the double call of ```call s:MapCR()``` at ```505``` and ```520```

**Comment by tpope** [comment]
This function's [twin](https://github.com/tpope/vim-endwise/blob/3719ffddb5e42bf67b55b2183d7a6fb8d3e5a2b8/plugin/endwise.vim#L134-L151) over in Endwise does support combining with delimiteMate's map. I've ported that behavior over. But delimitMate won't override an existing map, so in order for this to work, it will need to load before Eunuch.

> Wanted to at least add a var that lets deactivate the passive behaviour but even that can't figure out.

Such a var already exists:

```vim
let g:eunuch_no_maps = 1
```
