### ISSUE TITLE
eunuch-passive <CR> map breaks a custom imap <expr> <CR>

### ISSUE THREAD

**Issue by intelfx** [tpope/vim-eunuch#117]
I have a somewhat elaborate custom insert-mode mapping of `<CR>` designed to tweak behavior of [vimcomplete](https://github.com/girishji/vimcomplete) and make it coexist with [vim-stabs](https://github.com/Thyrum/vim-stabs):

https://github.com/intelfx/dotfiles/blob/a27c10f83c525229e1237fb4a8f436682409a49b/.vimrc#L458-L525

When adding vim-eunuch to the mix, every <kbd>\<CR></kbd> with autocompletion popup present just spits out `<Plug>(vimcomplete-skip)` verbatim.

I can "fix" this by dropping the `<script>` modifier on the "combined" CR map:

```diff
diff --git a/plugin/eunuch.vim b/plugin/eunuch.vim
index cbab46e..1878906 100644
--- a/plugin/eunuch.vim
+++ b/plugin/eunuch.vim
@@ -488,7 +488,7 @@ function! s:MapCR() abort
   if get(map, 'expr') && type(get(map, 'callback')) == type(function('tr'))
     lua local m = vim.fn.maparg('<CR>', 'i', 0, 1); vim.api.nvim_set_keymap('i', '<CR>', m.rhs or '', { expr = true, silent = true, callback = function() return vim.fn.EunuchNewLine(vim.api.nvim_replace_termcodes(m.callback(), true, true, m.replace_keycodes)) end, desc = "EunuchNewLine() wrapped around " .. (m.desc or "Lua function") })
   elseif get(map, 'expr') && !empty(rhs)
-    exe 'imap <script><silent><expr> <CR> EunuchNewLine(' . rhs . ')'
+    exe 'imap <silent><expr> <CR> EunuchNewLine(' . rhs . ')'
   elseif rhs =~? '^<cr>' && rhs !~? '<plug>'
     exe 'imap <silent><script> <CR>' rhs . '<SID>EunuchNewLine'
   elseif rhs =~? '^<cr>' || rhs =~# '<[Pp]lug>\w\+CR'
```

But, I assume that `<script>` is there for a reason and it isn't the right fix. Am I doing something wrong with the mapping I linked above? Or in general, do you perhaps have any ideas how to fix this properly?

**Comment by mirql** [comment]
hello! i guess there is same problem when using `mini.pairs` plugin (i have `lazyvim` preconfigured setup with big extended configuration)

so cursor moving after expansion of `(|<cr>)`, `{|<cr>}`, not working and i getting result `{\n|}` (or `{\n  |}`
