### ISSUE TITLE
Swap file warning with `:Move` (with `directory` set)

### ISSUE THREAD

**Issue by blueyed** [tpope/vim-eunuch#18]
I am experimenting with setting Vim's `'directory'` setting, to not clutter directories with swap files.

When using `:Move`, a swap file warning appears:

> Swap file "/home/user/tmp/vim/swapfiles/foo.swp" exists, overwrite anyway?

Since this is the expected behavior / the same/old file, there should be no warning.

**Comment by noscript** [comment]
Second to this, it's a bit annoying.

**Comment by noscript** [comment]
@blueyed I found a workaround by appending `//` to the swap directory path, e.g. `set dir=/tmp//`

```
:help dir

For Unix and Win32, if a directory ends in two path separators "//"
or "\\", the swap file name will be built from the complete path to
the file with all path separators substituted to percent '%' signs.
This will ensure file name uniqueness in the preserve directory.
On Win32, when a separating comma is following, you must use "//",
since "\\" will include the comma in the file name.
```

**Comment by blueyed** [comment]
Yes, I am using this myself already.
Thanks for the heads-up.
Let's close this issue then.
