### ISSUE TITLE
The commands do not work on Windows

### ISSUE THREAD

**Issue by Forethinker** [tpope/vim-eunuch#20]
I have tested vim-eunuch to be working on Linux with the same .vimrc fie, but I have trouble getting it to work on Windows. I have changed from:

```
fnamemodify(bufname(<q-args>),':p')
```

to 

```
bufname(expand('%')) 
```

on line 17, but it does not still work with `delete()`.
When I run `:call delete(bufname(expand('%')))` manually, it works. Do you have any idea?

**Comment by tpope** [comment]
Willing to revisit if anyone can reproduce this in 2022.
