### ISSUE TITLE
:Rename doesn't use Unix home directory correctly on Mac

### ISSUE THREAD

**Issue by andrewferrier** [tpope/vim-eunuch#22]
Steps to recreate:
- Open MacVim with vim-eunuch installed. Create a new file with `:new`. Enter content and save with `:w ~/Desktop/foo.txt`. As expected, `foo.txt` is created on the desktop.
- Rename the file with `:Rename ~/Desktop/bar.txt`. Rather than just renaming the file, it creates a new directory called `~` on the desktop, and puts the file in that, rather than evaluating it as the user's home directory.

**Comment by grr** [comment]
Would be nice if you could also use tab-complete with `:Rename`. I typically need to rename a file using most of it's original filename, such as adding a prefix or suffix to the original name.
