### ISSUE TITLE
Over-rides my user defined command for :W

### ISSUE THREAD

**Issue by xHN35RQ** [tpope/vim-eunuch#27]
I have this in my .vimrc, appearing before I load eunuch plugin, however the `:W` command in eunuch over-rides the below command:

```
" Allow saving a filename with spaces
" :W auto-escapes a filename before writing
command! -bang -nargs=* W :call W(<q-bang>, <q-args>)
function! W(bang, filename)
    :execute "w".a:bang." ". fnameescape(a:filename)
endfunction
```

Any ideas why this is happening? I can see that the plugin checks for the existence of `:W` so I'm guessing this check is failing for some reason.

Thanks!

**Comment by tpope** [comment]
I don't know why it would fail other than a Vim bug.

**Comment by xHN35RQ** [comment]
Ok. I'm using nvim so I'll report this to their repo. thanks.

**Comment by xHN35RQ** [comment]
If I remove `!=# 2` on https://github.com/tpope/vim-eunuch/blob/master/plugin/eunuch.vim#L168 then it works fine. Not sure why.

**Comment by xHN35RQ** [comment]
If I remove ` !=# 2` on https://github.com/tpope/vim-eunuch/blob/master/plugin/eunuch.vim#L168 then it works fine. Not sure why. I'll just edit my local instance of the plugin. thanks.

**Comment by tpope** [comment]
Because you changed it from checking for a W command to checking for *any*
command that starts with a W.

**Comment by xHN35RQ** [comment]
Oh! haha. I'm going to re-check my .vimrc and work on learning Vimscript better so I actually know what I'm doing. Thanks again for your help!
