### ISSUE TITLE
Use % to expand the name

### ISSUE THREAD

**Issue by mjacobus** [tpope/vim-eunuch#28]
Hey Tim

First of all, thank you for more this plugin, it is so useful!

Second, I would like to propose a minor enhancement.

```vim
:Rename %<tab> "to exapand the file path
```

This is very useful in case you need just to fix a typo, or add/remove a folder in the path. As for the moment the % wont expand.

Cheers!

**Comment by tpope** [comment]
That's a bit of a misfit because `%` means "path to current file" whereas `:Rename` takes a file name only. `:Move %<Tab>` works as you expect.
