### ISSUE TITLE
Completion for :Remove

### ISSUE THREAD

**Issue by stellarhoof** [tpope/vim-eunuch#29]
I'm sure you have thought about this @tpope. Is there any reason not to have file completion on `:Remove` ?

**Comment by tpope** [comment]
Only the fact it doesn't take an argument.

**Comment by azure-satellite** [comment]
I would love if I could remove a buffer in the buffer list without having to switch to it first

**Comment by tpope** [comment]
Have at it. The challenge is that there's no direct way to reload an inactive buffer. You'd have to switch to it, reload, and switch back.
