### ISSUE TITLE
SudoEdit filetype detection doesn't work with >= sudo-1.8.13

### ISSUE THREAD

**Issue by c-14** [tpope/vim-eunuch#31]
Modification of user environment in sudoedit was considered a bug and fixed in the 1.8.13 release.
https://bugzilla.sudo.ws/show_bug.cgi?id=688

I'm not sure it's possible to find out if vim is executed by sudoedit anymore. My current workaround is to create a shell function sudoedit() { SUDO_COMMAND="sudoedit $1" command sudoedit "$1" }

**Comment by tpope** [comment]
Good to know. Let me know if you find a way to determine the file name.

**Comment by timss** [comment]
Thanks for sharing, @c-14.

While looking for ways to use `sudoedit` with Vim I came across this topic as well. Posted an answer based on your workaround and background info:

http://vi.stackexchange.com/a/7810/5070
