### ISSUE TITLE
SudoWrite does not handle symlinks

### ISSUE THREAD

**Issue by blueyed** [tpope/vim-eunuch#34]
`SudoWrite` does not work with symlinks:

```
% echo foo > foo
% sudo chown root foo
% ln -s foo symlink
% vim -c 'norm o2' -c 'SudoWrite' -c q symlink
% cat foo
foo
```

The expected result would be to have "2" after "foo".

(Initially reported accidentally against https://github.com/chrisbra/SudoEdit.vim/issues/40#issuecomment-174661976)

**Comment by tpope** [comment]
This only happens when the symlink is owned by a different user, and even sudo thinks that's a bit obtuse:

    % sudo -e symlink
    sudo: symlink: Permission denied

But feel free to throw the appropriate `resolve()` in there.

**Comment by tpope** [comment]
Now that I think about it, sudo is probably rightfully guarding against a race condition.

**Comment by mvgrimes** [comment]
It looks like this a result of a change to sudo in version 1.8.15. My concern, is the lack of error message. Without any warning, there is a risk of data loss.

**Comment by tpope** [comment]
I can't reproduce this anymore. Probably got fixed in a refactor. Let me know if it's still an issue.

**Comment by tpope** [comment]
Did manage to reproduce in more specific circumstances. But I now that I think about it, sudo is right here. Writing to a symlink is dangerous. If I "fixed" this by adding a `resolve()`, I'd be recreating exactly the same security vulnerability sudo is trying to protect you from.

**Comment by tpope** [comment]
I have decided to compromise and resolve the symlink on `:SudoWrite!`, as a little undocumented treat for y'all.
