### ISSUE TITLE
Request: add buffer variable or user autocmd when sudo invoked

### ISSUE THREAD

**Issue by fourjay** [tpope/vim-eunuch#36]
I've been using sudowrite for system configuration in conjunction with some VCS. I'd like to be able to cue "smarter" behavior for this scenario, in this case adjust the behavior of the VCS calls to reflect a need for privileged invocation.

This seems like other commands might want to know this as well.

**Comment by tpope** [comment]
Currently the usual `BufWritePost` does *not* trigger, correct? That is my recollection about how `BufWriteCmd` works.
