### ISSUE TITLE
Request: also :Remove file from arglist

### ISSUE THREAD

**Issue by tommykey** [tpope/vim-eunuch#39]
When using :Remove on a buffer in arglist, also remove the corresponding file from the arglist.
(Renaming with :Move works as expected.)

**Comment by tpope** [comment]
This doesn't feel like a good fit. If we make `:Remove` call `:argdel %`, then `:Remove` followed by `:next` will skip over a file, because deleting the file from the argument list silently advanced us to the next file already. I don't think this is what most users would expect.
