### ISSUE TITLE
Add :Grep command

### ISSUE THREAD

**Issue by danijar** [tpope/vim-eunuch#41]
Grep recursively starting from the parent directory of the current file and add the results to the quickfix list.

**Comment by Denton-L** [comment]
There's already `:grep` for that.

**Comment by danijar** [comment]
Nice, it's just missing from the docs if I'm not mistaken.

**Comment by desjardinsm** [comment]
`:h :grep`

**Comment by danijar** [comment]
I see, didn't know that it comes with Vim by default.

**Comment by anh072** [comment]
you can use ack for this https://github.com/mileszs/ack.vim
