### ISSUE TITLE
Request: Copy inside containing directory ?

### ISSUE THREAD

**Issue by wichtounet** [tpope/vim-eunuch#43]
Hi, 

One thing that is very practical with the `Rename` command is that it works in the containing folder of the file and not in the current working directory. It would be great if vim-eunuch were to provide `Copy` that would do a copy of the file directly inside the file's containing directory. 

Thanks

**Comment by pokey** [comment]
@wichtounet see #47.  As described there, you can do `Copy` in the same directory by putting something like this in your .vimrc:

```
command! -bar -nargs=1 -bang RenameCopy saveas<bang> %:h/<args>
```

As discussed there, the command name `RenameCopy` could use some work :-), so would love any suggestions you may have.  And to just do `Copy` as equivalent to `Move`, the `saveas` command does the trick.

**Comment by tpope** [comment]
To elaborate on the answer I gave there, the biggest problem with just directly inputting `:saveas %:h/<Tab>` is literally "I have to type a couple of annoying punctuation marks". Which, okay, I feel you, but I'm not going to add a confusingly named command just to spare you a bit of punctuation. Come up with a *great* name and I'm on board.
