### ISSUE TITLE
Provide a means to disable auto-population of buffer with contents of `/etc/init.d/skeleton`.

### ISSUE THREAD

**Issue by cmhamill** [tpope/vim-eunuch#46]
I have been unpleasantly surprised to find that if I ever create a file with `/init.d/` as a component of its full path, I get the contents of `/etc/init.d/skeleton` in the buffer. I'd like the means to disable this, as I happen to use `init.d` folders for other purposes here and there. In addition, I already have a means of templating new files if I ever have need of it.

Thanks!

**Comment by tpope** [comment]
That good enough?

**Comment by cmhamill** [comment]
Works great for me. Thanks for the obscenely quick response.
