### ISSUE TITLE
SudoWrite does not report failure

### ISSUE THREAD

**Issue by y** [tpope/vim-eunuch#48]
Calling \:SudoWrite on a buffer for a file that has been removed is reported as success

Steps to reproduce:
* `mkdir /tmp/ve/`
* `touch /tmp/ve/file.txt`
* `vim /tmp/ve/file.txt`
* in terminal: `rm -rf /tmp/ve/`
* `:SudoWrite`

The buffer is now marked as nomodified, but the file does not actually exist on disk.

However, if you use `!sudo tee %` instead of `:SudoWrite`, it properly reports the error:
`E211: File "/tmp/ve/file.txt" no longer available`

**Comment by tpope** [comment]
[This is the command that is actually used](https://github.com/tpope/vim-eunuch/blob/dcd29a00eb708be211d856afd3fddfbff7bc6208/plugin/eunuch.vim#L132), if you want to debug further.

**Comment by y** [comment]
So the error is displayed in gui vim, but silenced in console vim (which is what I was testing before). 
It looks like that was added here: https://github.com/tpope/vim-eunuch/pull/7, to avoid an extra "press ENTER" prompt. But it's silencing true error message under console and adding an extra "press ENTER" prompt under GUI.

So even though a message is displayed in the gui, sudo doesn't exit with an error, so the following line when &modified is set, it's set wrong because v:shell_error is false. You can verify with `echo abc | env SUDO_EDITOR=tee VISUAL=tee sudo -e /tmp/asdfa/asdfa/asdf > /dev/null` 

I think that's as far as I can take this.
