### ISSUE TITLE
Copy as

### ISSUE THREAD

**Issue by thooams** [tpope/vim-eunuch#49]
Is it possible to create a copy function which copy file in the same dir with another name ?
Eq. `:CopyAs my_file.rb`
like: `:w %:p:h/my_file.rb`

**Comment by rawaludin** [comment]
Native `:saveas` should do the feature.

**Comment by fturcheti** [comment]
> Native `:saveas` should do the feature.

Not exactly. Comparing to other eunuch commands, `:CopyAs` would work like `:Rename`, i.e., relative to the current file's containing directory, and different from `:Move`, that's relative to the current working directory.

To illustrate it:

Imagine your working directory, as in `:pwd`, is `/project`, but you're editing `/project/src/somefile.ext`. Then you want to create a copy of this file and name it `anotherfile.ext`. 

- With `:saveas anotherfile.ext`, the new file would be created at `/project`. To keep the copy in the same directory of the original file, you'd have to use `:saveas %:p:h/anotherfile.ext`.
- With the proposed `CopyAs`, typing `:CopyAs anotherfile.ext` would create the new `anotherfile.ext` at `/project/src`, alongside the original `somefile.ext`.

**Comment by rawaludin** [comment]
I would do :saveas %<tab><c-w><c-w>newfile.txt

**Comment by fturcheti** [comment]
You're right @rawaludin, it's easy to use a native command in this case – actually, I'm already doing that. But the request matches the purpose of this plugin, that's to provide "Vim sugar for the UNIX shell commands".

So it seems to make sense having a command like the suggested `:CopyAs` (or `:SaveAs`). It is simply some sugar over the built-in `:saveas` and that's the thing of vim-eunuch.

**Comment by tpope** [comment]
I'm having trouble getting past the name. How do you get from "`:saveas` relative to the current file's directory" to `:CopyAs`?

**Comment by fturcheti** [comment]
I endorsed the feature request but, personally, I prefer `:SaveAs`.

**Comment by tpope** [comment]
That's less random, but still raises the same question.

Why provide `:SaveAs` and not also `:Edit`, `Read`, `:Write`, :WQ`, `:File`, `:VSplit`, etc?

**Comment by fturcheti** [comment]
I was looking at the perspective that the suggested `:CopyAs`/`:SaveAs` is a good companion to the already provided commands `:Rename` and `:Move`, and just that. But now I see that `:Rename` and `:Move` can't be achieved with a single native command,  whereas `:CopyAs`/`:SaveAs` can.

So I understand your point of view, and now I see the implications this addition could trigger.

**Comment by tpope** [comment]
To sum up the arguments for providing `:Rename` as an alias `:Move %:h/`:

* It's an extremely common operation.
* It's a variation of something Eunuch has already taken responsibility for.
* There's a single, obvious, easily remembered name for it.

Compare to `:SaveAs`:

* It's common mainly as a poor man's template system. That is, it's useful in a pinch, but if you're doing it a million times a day, there's probably a better solution.
* It's a variation of a built-in.
* I can't think of a good name.

So yeah, it'd be a questionable addition with a good name. I don't think I'll be adding it with a bad name.

**Comment by tpope** [comment]
Try adding `return [domain_pattern, base]` after this line and see what it returns then:

https://github.com/tpope/vim-rhubarb/blob/b6cbbb0ad3e22870a3cd8d79a22722c63d98d18b/autoload/rhubarb.vim#L33

**Comment by dylan-chong** [comment]
How about `:Duplicate`?

**Comment by fturcheti** [comment]
That's definitely a better name!
