### ISSUE TITLE
Did I hallucinate Git integration?

### ISSUE THREAD

**Issue by replaid** [tpope/vim-eunuch#50]
I somehow formed the impression that eunuch `:Rename`s etc. made the corresponding changes to a Git repo. But on my new machine it isn't as I think I remember. Is there a tpope plugin I'm missing that makes this so? If there is, then this is a documentation request that a note be added about how to enable that coolness.

Thanks for great tools.

**Comment by tpope** [comment]
Fugitive has `:Gmove` and `:Gremove`. `:Grename` would be a reasonable addition.
