### ISSUE TITLE
E382: Cannot write, 'buftype' option is set

### ISSUE THREAD

**Issue by darthdeus** [tpope/vim-eunuch#6]
Sometimes when I save a file, I get the following error. I've identified that the 38. plugin is `eunuch`

```
"user.py" 198L, 5545C written
Error detected while processing function <SNR>38_W:
line    8:
E382: Cannot write, 'buftype' option is set
Press ENTER or type command to continue
```

It happens only sometimes, not always. But it sometimes occurs multiple times in a row, when I do 2-3 `:w` until it stops happening. I haven't really figured out when it is happening.

[Here's my `~/.vimrc` if that helps](https://github.com/darthdeus/dotvim/blob/master/vimrc)

**Comment by Vinni-Cedraz** [comment]
I found that saving and exiting at the same time with the :x commands gets around the problem but I also don't know the reason it happens.
