### ISSUE TITLE
Request: can I have "Duplicate" ? 

### ISSUE THREAD

**Issue by eduardoarandah** [tpope/vim-eunuch#62]
Duplicate a file in same dir is very common, can you consider it? 
thanks!

**Comment by hauleth** [comment]
Why not use `:saveas %:h/duplicate`?

**Comment by eduardoarandah** [comment]
yeah, I just want the convenience of creating the file and then open it

`:Duplicate copy.txt`

I guess it's super easy to create the function

**Comment by eduardoarandah** [comment]
Can you help me with 3rd line? 
I don't know any vimscript 

the idea is type C-R then = and then expand current filename, so the user can type another filename. 

```
function! s:duplicate()
  let n = input("Name: ")
  <C-R>=fnameescape(expand("%:p"))<CR>
  if n != ''
    execute "w " . n 
    execute "e " . n 
  endif
endfunction
:command! -bar Duplicate :call s:duplicate()
```

**Comment by eduardoarandah** [comment]
This function already works, but you have to type the file extension, and that's boring because extension is always the same


```
function! s:duplicate(name)
  if a:name != ''
    execute "w %:h/" . a:name 
    execute "e %:h/" . a:name 
  endif
endfunction
:command! -nargs=1 -bar Duplicate :call s:duplicate(<f-args>)

```
# Use: 
``` 
Duplicate copy.txt
```

**Comment by hauleth** [comment]
How is that different from `:saveas %:h/name`?

**Comment by eduardoarandah** [comment]
> How is that different from `:saveas %:h/name`?

Man.. that's like an alien talking. 
Ease of use must be a thing before microsoft takes all developers to vscode imho

**Comment by tpope** [comment]
The word "duplicate" does not mean "create a copy in the current directory with the same extension" so I don't think it's any less alien than `:saveas %:h/`. I think a weirdly named command like that would be more confusing than helpful in eunuch.vim.

But by all means create one for your own use. `%:e` will give you the extension.
