### ISSUE TITLE
Chmod does not respect umask for +x/-x

### ISSUE THREAD

**Issue by theburge** [tpope/vim-eunuch#66]
The implementation of `+x` and `-x` do `ugo+x` and `ugo-x` respectively, which is not what [`chmod(1)`](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/chmod.html) does when the umask includes any of those bits.

Thoughts on implementation: AFAIK, there's no way to extract the umask in Vim without invoking `umask(1)`, which somewhat undermines the implementation of `Chmod` in terms of `getfperm`/`setfperm`. However, caching the result of invoking the program is probably a reasonable thing to do since there's no way to change the umask either.

**Comment by tpope** [comment]
Good diagnosis, with one small oversight that `umask` isn't a `(1)`, it's a shell built-in. And I'm not optimistic about using it:

```
$ bash -c umask
0007
$ zsh -c umask
007
$ tcsh -c umask
7
```

The primary purpose of using the `s:fcall('setfperm',...)` abstraction is to enable toggling the execute bit on index blobs in Fugitive. The secondary purpose is a tiny performance improvement. I am totally cool to throw out the latter.

**Comment by theburge** [comment]
Thanks (belatedly) for the fix and rationale!
