### ISSUE TITLE
Rename Move does not work when only case is changed

### ISSUE THREAD

**Issue by pinggit** [tpope/vim-eunuch#68]
I found very often (not sure everytime) that, when I change a filename from "Abc-Def.txt" to "abc-def.txt", neither Rename nor Move works. is this expected?
I'm with Vim 8.1 on wsl, if that matters.

**Comment by tpope** [comment]
Can confirm I'm seeing this too on macOS. Vim's built-in `:saveas` has the same problem—calling `:saveas abc-def.txt` keeps the name `Abc-Def.txt`—and that makes finding a solution tricky.
