### ISSUE TITLE
Request: :SudoEdit should re-evaluate what the filetype should be.

### ISSUE THREAD

**Issue by 0xACE** [tpope/vim-eunuch#70]
Hello, `:SudoEdit` doesn't deal well with files which the user has no permission of listing/reading.

`sudo -e ./protected_folder/protected_file.yaml` opens the file with the correct filetype set.

`:SudoEdit` loads the file but filetype is set as nothing.

**Comment by tpope** [comment]
`:SudoEdit` [reloads the file](https://github.com/tpope/vim-eunuch/blob/36c5974a74b202ade1eb40dabd134afb2fdfdbe0/plugin/eunuch.vim#L264), which should trigger the file type detection, and indeed, that's what I'm seeing. I cannot reproduce. There's nothing more I can do here but do report back if you figure anything out.

**Comment by 0xACE** [comment]
Sorry, seems like i was on 0971b4c it works as expected in `master`
