### ISSUE TITLE
Is $SECURITYSESSIONID needed to check?

### ISSUE THREAD

**Issue by delphinus** [tpope/vim-eunuch#72]
I'm using NeoVim and know `:SudoWrite` cannot work by default settings. So I searched issues and found a workaround in https://github.com/tpope/vim-eunuch/issues/56#issuecomment-626665562 .

I tried this workaround but still it did not work. So I invested the source and found here.

https://github.com/tpope/vim-eunuch/blob/36c5974a74b202ade1eb40dabd134afb2fdfdbe0/plugin/eunuch.vim#L189

@tpope says this line detects the env is NeoVim in local ( https://github.com/tpope/vim-eunuch/issues/45#issuecomment-373882508 ).  But is `$SECURITYSESSIONID` needed to check? At least in my env (macOS Mojave 10.14.6), `$SECURITYSESSIONID` is always empty even in local.

----

For a stopgap measure, I wrote below in `init.vim` and successfully `:SudoWrite` works! thx @TSFoster !

```vim
if $SECURITYSESSIONID == ''
  let $SECURITYSESSIONID = 'dummy'
endif
let $SUDO_ASKPASS = '/path/to/macos-askpass'
```

**Comment by tpope** [comment]
I borrowed this check from Git, which has since changed the conditional: https://github.com/git/git/commit/be537e43ca8c6e38a3cf7024b28d6daf54611132. Does adding a check for `$TERM_PROGRAM` fix it?

**Comment by delphinus** [comment]
Ah, I got the reason for the code clearly by the comment in git's commit. `$DISPLAY . $SECURITYSESSIONID . $TERM_PROGRAM` seems sufficient. I will PR for this.
