### ISSUE TITLE
Cfind not restoring back the value of grepprg

### ISSUE THREAD

**Issue by Andrikin** [tpope/vim-eunuch#74]
Hi! I was testing Cfind command and I notice that after I use it, grepprg value was not restoring for his previous value. I set a different variable name in s:Grep and I was able to get it work. I think that was a conflit between the function variable name and the local option name beeing the same. I'm just speculating here, because I set rg for grepprg. Big fan of your work! The Pope of Vim! :)

**Comment by tpope** [comment]
What Vim version?

**Comment by Andrikin** [comment]
I'm so ashamed, it was my mistake. I tested eunuch without vimrc file or any other package, and it played great. Tested with my configuration and it work great. Probably it was me messing around with grepprg. My Vim version is 8.2.801.
