### ISSUE TITLE
[Feature request] Automatically :Mkdir before writing a file in a nonexistent path

### ISSUE THREAD

**Issue by danielfalbo** [tpope/vim-eunuch#76]
I have
```vim
function s:Mkdir()
  let dir = expand('%:p:h')

  if dir =~ '://'
    return
  endif

  if !isdirectory(dir)
    Mkdir " vim-eunch's Mkdir
  endif
endfunction

autocmd BufWritePre * call s:Mkdir()
```
in my vimrc to create non-existent dirs before writing buffers. What do you think about making this a vim-eunch feature?

**Comment by tpope** [comment]
I don't want to encourage this workflow, as Vim isn't really built to accommodate it. If you edit a file that doesn't belong to a directory, Vim assumes it isn't really a file at all, and changes how some commands like `:cd` work in confusing ways.

Also, note that `if dir =~ '://'` catches just one of several edge cases. Try editing a zip file for example. `if dir =~# '^\a\a\+:` is my go-to conditional for this sort of stuff, but even that is a bit lax for something as invasive as a plugin automatically creating directories.
