### ISSUE TITLE
CFind doesn't work with double quotation marks

### ISSUE THREAD

**Issue by ConorHK** [tpope/vim-eunuch#81]
CFind doesn't see arguments wrapped in `""` opposed to `''`.

**Example:**
Console:
```
~/repositories/distributed_systems/customer ──── ─ find . -name "*.java"
./src/main/java/customer/Customer.java
```
In vim:
```
:Cfind . -name "*.java"
```
Becomes
```
:!find . -name | tee /tmp/nvimfIqCon/4
find: missing argument to `-name'
```

**Comment by tpope** [comment]
This wasn't a bug; it was a deliberate decision to allow chaining like `:Cfind .|AnotherCommand`, which means also allowing `:Cfind . " comment`. I'm tentatively changing that decision.
