### ISSUE TITLE
Feature request: "Duplicate"? Same as ":saveas", but saves to the same directory

### ISSUE THREAD

**Issue by Hubro** [tpope/vim-eunuch#88]
Here's an issue I keep having lately:

- I have a deeply nested file open in the editor
- I want to make a duplicate of the file in the same directory
- I don't want to type out the entire path

Basically it would be nice to have a command like ":saveas", but without having to type the entire path to the file.

**Comment by tpope** [comment]
This is #54 with a better verb. I'm of the mind that this is too small of a value-add on top `:saveas %:h/`, but there's enough demand that I'm getting close to caving. So watch that issue.

**Comment by Hubro** [comment]
I keep forgetting that `%:h` (and other similar shortcuts) exist, and I use them rarely enough that I never remember the syntax when I need them... :disappointed:
