### ISSUE TITLE
SudoWrite should call redraw! before call to sudo

### ISSUE THREAD

**Issue by grr** [tpope/vim-eunuch#90]
In terminal vim when calling SudoWrite, the command isn't cleared, it's written over by the password prompt, so the 'e' of SudoWrite is still displayed at the cursor:
<img width="105" alt="Screen Shot 2022-04-13 at 17 10 36" src="https://user-images.githubusercontent.com/690894/163279759-bbef4ca4-75d6-4604-9062-a1c04360852f.png">
This isn't too noticeable but when i tried `silent! SudoWrite`, it resulted in:
<img width="159" alt="Screen Shot 2022-04-13 at 17 27 45" src="https://user-images.githubusercontent.com/690894/163280734-25c1dead-de8c-44ba-9ef8-ef52b29af508.png">
Executing `radraw!` before `write!` in `s:SudoWriteCmd()` resolves this.

**Comment by tpope** [comment]
Using `redraw|echo` has the added advantage of avoiding flicker.
