### ISSUE TITLE
Asynchronous support for :Clocate

### ISSUE THREAD

**Issue by teoljungberg** [tpope/vim-eunuch#92]
Commands usch as locate(1) can be slow on macOS, and this makes eunuch's `:Clocate` also on the slower side. I wonder if that could be mitigated by adding dispatch.vim support for those commands, or adding job support if supported.

How would such an example patch look, is it feasible to do, and what approach would be best?

**Comment by tpope** [comment]
We're already abusing built-ins by screwing with `'shellpipe'`. Adding dispatch.vim would make it impossible to see error messages.

> Commands such as locate(1) can be slow on macOS

I just tried a cold run of `locate vim.vim` and it took 350 milliseconds.  Might be time for a trip to the genius bar.

It might be worth looking into directly using `job_start()`/`jobstart()` at some point. Those make it easy to distinguish between stdout and stderr, which would be an improvement on the hack we're currently using.

**Comment by teoljungberg** [comment]
> I just tried a cold run of locate vim.vim and it took 350 milliseconds. Might be time for a trip to the genius bar.

Definitely, for comparison:

```
%  time locate vim.vim
# ...
locate vim.vim  3.11s user 0.11s system 65% cpu 4.934 total
```

As for `job_start` and `jobstart`- I'll see if I can prepare a patch for adding support for them.

**Comment by tpope** [comment]
Honestly 5 seconds is borderline acceptable. Not like that's enough time to meaningfully multitask.

The pitch is stronger for `find`.

**Comment by teoljungberg** [comment]
Agreed.

As all of the commands use `:grep` under the hood, they would all get the improvement and gain.
