### ISSUE TITLE
EunuchNewLine("\r") being printed on every new line

### ISSUE THREAD

**Issue by kadimisetty** [tpope/vim-eunuch#96]
`EunuchNewLine("\r")` being inserted at cursor on hitting `<CR>` in insert mode. This  started with the new update, so while I don't understand why, I'm assuming it has to do with the recent commit 74e0e1662cc9ed3d58ba3e3de20eb30ac4039956

There is a similar error with the similar update in `endwise` - `EndwiseAppend("\r")`. And with both the plugins together, on every `<CR>` in insert mode,  there is `EunuchNewLine(EndwiseAppend("\r"))` being inserted at cursor.

Do let me know if there's anything I can do for clarification's sake.  

version- vim 8.2

**Comment by tpope** [comment]
What does `:verbose imap <CR>` show?

**Comment by kadimisetty** [comment]
With both eunuch and endwise:
```
i  <CR>          EunuchNewLine(EndwiseAppend("\r"))<Plug>CloserClose
        Last set from ~/.vim/plugged/vim-closer/autoload/closer.vim line 22

```

**Comment by kadimisetty** [comment]
The part
`Last set from ~/.vim/plugged/vim-closer/autoload/closer.vim line 22`
seems to indicate fixing this issue might not have anything to do with either eunuch or endwise after all. The recent update might have caused a regression in another plugin I use [vim-closer](https://github.com/rstacruz/vim-closer) which advertises itself as a companion to endwise. I suppose they'll have to adjust something on their end. 

Unless there's a benefit to keeping this issue open, if you deem it sensible please close this issue.

**Comment by tpope** [comment]
vim-closer needs to handle `<expr>` maps. Copying the approach used in Endwise/Eunuch would likely work.

You can probably work around by arranging for vim-closer to load first.

**Comment by kadimisetty** [comment]
That makes sense. Thanks for your help!
