### ISSUE TITLE
Disabling auto-shebang on enter

### ISSUE THREAD

**Issue by casey** [tpope/vim-eunuch#98]
Rust source code files often start with something like:

```
#![allow(clippy::too_many_arguments)]
```

Which vim-eunich will turn into:

```
#!/usr/bin/env [allow(clippy::too_many_arguments)]
```

Is there a way to turn this off?

**Comment by tpope** [comment]
There's `g:eunuch_no_maps`. But I'll fix it.

**Comment by casey** [comment]
I think documenting `g:eunuch_no_maps` might be enough, I looked in the docs and couldn't find it, and looked at the code but couldn't figure out.
