### ISSUE TITLE
Documentation for hooking into passive behaviors is outdated

### ISSUE THREAD

**Issue by anichols-ht** [tpope/vim-eunuch#99]
First, thank you for documenting the passive behavior. That definitely helped me figure out how to solve my issue.

The docs mention using `EunuchCR()`, however, I don't see a function by that name. I think it's supposed to be `EunuchNewLine()`. I also couldn't get that to work as is, I had to call it like `EunuchNewLine("\r")` otherwise `line('.') != 2` was coming back true and returning empty string. Maybe that last part is specific to my setup, idk.

**Comment by tpope** [comment]
Not even out of date, it's just wrong.

Most people shouldn't need to call `EunuchNewLine()` at all as Eunuch is pretty good at combining with other maps. I'll update the documentation to reflect that.

**Comment by anichols-ht** [comment]
Yeah, in case you just want context for why it's necessary for me . . . I just started using coc for completion and I like to use enter for selecting an entry, but I couldn't get that to work unless I defined it in an `after` function, and that made both endwise and eunuch functionality not work, so I had to call them manually.

**Comment by tpope** [comment]
That `coc#pum#visible()` ternary that everyone copies and pastes into their vimrc? Should work fine.

**Comment by anichols-ht** [comment]
Oh yeah, I'm realizing it's . . . complicated. Long story short, I also use ultisnips so I wrote tab and shift tab in functions because they were getting complicated, so then I also just wrote the enter one in a function even though that's not necessary since enter isn't used by ultisnips. The ternary with `<expr>` probably does work fine.
